name: Build and deploy Python project to Azure Function App - hfo-repo-crawler-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/repo_crawler' # Caminho correto para o projeto
  PYTHON_VERSION: '3.11' # Versão do Python a ser usada
  FUNCTIONS_WORKER_RUNTIME: "python"
  GITHUB_REPO: "MicrosoftDocs/azure-docs"
  AZURE_STORAGE_CONTAINER: "rag_data"
  FOLDERS_TO_INCLUDE: "['articles/azure-functions']"
  DAYS_AGO: "3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/venv
          source ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip . -x "venv/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          mkdir -p ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          unzip release.zip -d ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'hfo-repo-crawler-test'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DCD828CFEC0B41AD838856F606530675 }}
        env:
          FUNCTIONS_WORKER_RUNTIME: ${{ env.FUNCTIONS_WORKER_RUNTIME }}
          GITHUB_REPO: ${{ env.GITHUB_REPO }}
          AZURE_STORAGE_CONTAINER: ${{ env.AZURE_STORAGE_CONTAINER }}
          FOLDERS_TO_INCLUDE: ${{ env.FOLDERS_TO_INCLUDE }}
          DAYS_AGO: ${{ env.DAYS_AGO }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
